/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 dead_city.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dead_city.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.Model001_Material092_7} />
        <mesh geometry={nodes.Object_10001.geometry} material={materials.Model001_Material092_7} />
        <mesh geometry={nodes.Object_10002.geometry} material={materials.Model001_Material092_7} />
        <mesh geometry={nodes.Object_100.geometry} material={materials.Model001_Material092_92} position={[0, 0, 0.079]} />
        <mesh geometry={nodes.Object_100001.geometry} material={materials.Model001_Material092_92} position={[0, 0, 0.079]} />
        <mesh geometry={nodes.Object_100002.geometry} material={materials.Model001_Material092_92} position={[0, 0, 0.079]} />
        <mesh geometry={nodes.Object_100003.geometry} material={materials.Model001_Material092_92} position={[0, 0, 0.079]} />
        <mesh geometry={nodes.Object_100004.geometry} material={materials.Model001_Material092_92} position={[0, 0, 0.079]} />
        <mesh geometry={nodes.Object_100005.geometry} material={materials.Model001_Material092_92} position={[0, 0, 0.079]} />
        <mesh geometry={nodes.Object_100006.geometry} material={materials.Model001_Material092_92} position={[0, 0, 0.079]} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.Model001_Material092_93} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.Model001_Material092_94} position={[0, 0, 0.005]} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.Model001_Material092_95} position={[0, 0, -0.004]} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Model001_Material092_8} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Model001_Material092_9} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Model001_Material092_10} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Model001_Material092_11} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Model001_Material092_12} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Model001_Material092_13} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Model001_Material092_14} />
        <mesh geometry={nodes.Object_18001.geometry} material={materials.Model001_Material092_15} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Model001_Material092_16} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.Model001_Material092} />
        <mesh geometry={nodes.Object_2001.geometry} material={materials.Model001_Material092} />
        <mesh geometry={nodes.Object_2002.geometry} material={materials.Model001_Material092} />
        <mesh geometry={nodes.Object_2003.geometry} material={materials.Model001_Material092} />
        <mesh geometry={nodes.Object_2004.geometry} material={materials.Model001_Material092} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Model001_Material092_17} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Model001_Material092_18} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Model001_Material092_19} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Model001_Material092_20} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Model001_Material092_21} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Model001_Material092_22} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Model001_Material092_23} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Model001_Material092_24} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Model001_Material092_25} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Model001_Material092_26} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Model001_Material092_0} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Model001_Material092_27} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Model001_Material092_28} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Model001_Material092_29} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Model001_Material092_30} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Model001_Material092_31} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Model001_Material092_32} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Model001_Material092_33} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Model001_Material092_34} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Model001_Material092_35} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Model001_Material092_36} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Model001_Material092_1} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Model001_Material092_37} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Model001_Material092_38} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Model001_Material092_39} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Model001_Material092_40} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Model001_Material092_41} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Model001_Material092_42} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Model001_Material092_43} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Model001_Material092_45} position={[0, 0, 0.224]} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Model001_Material092_2} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Model001_Material092_47} position={[0, 0, 0.177]} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Model001_Material092_3} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Model001_Material092_58} position={[0, 0, 0.143]} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.Model001_Material092_59} position={[0, 0, 3.829]} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Model001_Material092_60} position={[0, 0, 0.072]} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Model001_Material092_61} position={[0, 0, 0.176]} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Model001_Material092_63} position={[0, 0, 0.147]} />
        <mesh geometry={nodes.Object_67001.geometry} material={materials.Model001_Material092_63} position={[0, 0, 0.147]} />
        <mesh geometry={nodes.Object_67002.geometry} material={materials.Model001_Material092_63} position={[0, 0, 0.147]} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Model001_Material092_64} position={[0, 0, 0.18]} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Model001_Material092_4} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Model001_Material092_66} position={[0, 0, 0.011]} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Model001_Material092_67} position={[0, 0, 0.145]} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Model001_Material092_68} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Model001_Material092_69} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Model001_Material092_70} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.Model001_Material092_71} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.Model001_Material092_72} />
        <mesh geometry={nodes.Object_76001.geometry} material={materials.Model001_Material092_72} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.Model001_Material092_73} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Model001_Material092_73} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.Model001_Material092_73} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Model001_Material092_5} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Model001_Material092_74} />
        <mesh geometry={nodes.Object_80001.geometry} material={materials.Model001_Material092_74} />
        <mesh geometry={nodes.Object_80002.geometry} material={materials.Model001_Material092_74} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81001.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81002.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81003.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81004.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81005.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81006.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81007.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81008.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_81009.geometry} material={materials.Model001_Material092_75} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.Model001_Material092_76} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.Model001_Material092_76} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.Model001_Material092_76} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.Model001_Material092_77} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.Model001_Material092_78} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.Model001_Material092_79} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.Model001_Material092_80} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Model001_Material092_81} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Model001_Material092_6} />
        <mesh geometry={nodes.Object_90001.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90002.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90003.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90004.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90005.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90006.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90007.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90008.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_90009.geometry} material={materials.Model001_Material092_82} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Model001_Material092_83} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.Model001_Material092_84} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Model001_Material092_85} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.Model001_Material092_86} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.Model001_Material092_87} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.Model001_Material092_88} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.Model001_Material092_89} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.Model001_Material092_90} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.Model001_Material092_91} position={[0, 0, 0.125]} />
      </group>
    </group>
  )
}

useGLTF.preload('/dead_city.gltf')
