/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 bed.glb 
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bed-1ebf05f2b2ae4d3cbbaed318c625b237
Title: Bed
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bed(props) {
  const { nodes, materials } = useGLTF('/assets/models/scene2/bunker/bed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.019} />
    </group>
  )
}

useGLTF.preload('/assets/models/scene2/bunker/bed.glb');
